apiVersion: v1 

2 

kind: Service 

3 

metadata: 

4 

name: medicore-service 

5 

spec: 

6 

selector: 

7 

app: medicore-app 

8 

type: NodePort 

9 

ports: 

10 

- port: 5001 

11 

targetPort: 5001 